#!/usr/bin/env bash
# This script checks for missed REPLACEME's

set -euo pipefail

SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

cd $SCRIPT_DIR

echo "Checking for any missed REPLACEME's..." >&2
echo

grep -r REPLACEME_ | grep -v .swp | grep -v ^.git | grep -v docs
if [ $? == 0 ]
then
    echo ""
    echo "You missed REPLACEME's in the above files. Don't try to install yet." >&2
else
    echo "You've hit all REPLACEME's. If you did those right then you should be good to use raven!" >&2
fi

if [ "$(id -u)" -eq 0 ]; then
    gum confirm --default=false "WARNING: You shouldn't use run this script as the root user. Proceed Anyway? "
fi

if [ ! -d "$HOME" ]
then
    gum confirm --default=false "ERROR: For some reason $HOME doesn't exist for user $(whoami). Create it? "
fi

if [ ! -d "$HOME/raven-machines" ]; then
    git clone https://github.com/digital-raven/raven.git "$HOME/raven-machines"
fi

cd $HOME/raven-machines

# Select hostname
HOSTNAME=$(gum input --prompt "What will you name your AC? " --placeholder "nightfall")

        # Git username and email
        if gum confirm --default=false "(Optional) Enter name and email you use for git commits?; then
          GIT_USERNAME=$(gum input --prompt "Enter your name for git commits: ") --placeholder "Raven"
          GIT_EMAIL=$(gum input --prompt "Enter your email for git commits: ") --placeholder "raven@rubicon.aleeas.com"
        fi

        # Select timezone
        TIMEZONE=timedatectl list-timezones | gum choose --height=30

        # Select locale
        LOCALE="en_US.UTF-8"
        if gum confirm --default=false "Select a locale other than $LOCALE? "; then
          LOCALE=$(wget -qO - 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=localedata/SUPPORTED' | sed -s 's/\\//' | tail -n +4 | gum choose --height=40 --header="Supported Locales")
        fi

        # Disk selection
        sda_devices="$(lsblk -JpS -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"
        nvme_devices="$(lsblk -JpN -o NAME,VENDOR,MODEL,REV,SERIAL,SIZE)"

        TARGET_DISK=$(echo "$sda_devices" \
          "$nvme_devices" | jq -s '[.[].blockdevices[]] | map({name, vendor, model, rev, serial, size})' | jq -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' | gum table) | awk -F, '{print $1}'

        gum confirm  --default=false \
          "This will erase $TARGET_DISK and format it for Raven. Is this correct?"

        echo "Partitioning Disks"
        sudo nix run github:nix-community/disko \
        --extra-experimental-features "nix-command flakes" \
        --no-write-lock-file \
        -- \
        --mode zap_create_mount \
