#!/usr/bin/bash

# get the absolute path of the script
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

cd $SCRIPT_DIR

if [ ! -d ./HyDE ]
then
    git clone --depth 1 https://github.com/prasanthrangan/hyprdots ./HyDE
fi

if [ "$1" == init ]
then
    ../raven-minimal/update init

    # Install HyDE
    cd ./HyDE/Scripts
    ./install.sh
else
    ../raven-minimal/update
fi

# Update HyDE
cd $SCRIPT_DIR
cd ./HyDE/Scripts
./install.sh -r
