#!/usr/bin/bash -e

# get the absolute path of the script
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

cd $SCRIPT_DIR

# Update this repo
git fetch origin
git checkout origin/master

# Install yay. Can't be done as root.
if [ ! -x /usr/bin/yay ]
then
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ..
    rm -rf yay
fi

# Docker. Groups require restart.
if [[ $(groups) !~ docker ]]
then
    sudo groupadd -r docker
    sudo gpasswd -a master docker
    yay -S docker
else
    # nordvpn requires docker
    yay -S $(cat aur_packages)
fi

# NordVPN groups. Will apply on restart
if [[ ! $(groups) =~ nordvpn ]]
then
    sudo groupadd -r nordvpn
    sudo gpasswd -a master nordvpn
fi

# Stop there if not doing first time-initialization
if [ "$1" != init ]
then
    exit 0
fi

# First time initialzation
# bash
cp resources/bash/bashrc ~/.bashrc
cp resources/bash/inputrc ~/.inputrc

# fish
cp -r resources/fish ~/.config/fish

# zsh
wget -O ~/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

# vim. Run :PlugInstall on first run. Then test openai key with :AI Hello!
cp resources/vimrc ~/.vimrc
